development:
    # Special key for development
    ABQIAAAAnfs7bKE82qgb3Zc2YyS-oBT2yXp_ZAY8_ufC3CFXhHIE1NvwkxSySz_REpPq-4WZA27OwgbtyR3VcA

test:
    # Special key for development
    ABQIAAAAnfs7bKE82qgb3Zc2YyS-oBT2yXp_ZAY8_ufC3CFXhHIE1NvwkxSySz_REpPq-4WZA27OwgbtyR3VcA

production:
    ABQIAAAAfrpJEDT0B9Z2RslL1QOA3hSjsDzyEnQqjTTANTN8BNClmESL5xTeQFl1Iyk_xH73Qj-3VFfgoYYdRw
